import { createContext, useContext, useEffect, useState } from "react";

const STRINGS = {
  fr: {
    // Sidebar
    "sidebar.workspace": "Workspace",
    "sidebar.dashboard": "Dashboard",
    "sidebar.search": "Recherche",
    "sidebar.chat": "Assistant IA",
    "sidebar.consultations": "Consultations",
    "sidebar.admin": "Administration",
    "sidebar.users": "Utilisateurs",
    "sidebar.settings": "Paramètres",

    // Dashboard
    "dashboard.greeting.morning": "Bonjour",
    "dashboard.greeting.afternoon": "Bon après-midi",
    "dashboard.greeting.evening": "Bonsoir",
    "dashboard.subtitle":
      "Votre copilote fiscal — recherche, conseil et consultations.",
    "dashboard.askQuestion": "Poser une question",
    "dashboard.newConsultation": "Nouvelle consultation",
    "dashboard.kpi.consultations": "Consultations",
    "dashboard.kpi.consultationsHint": "au total",
    "dashboard.kpi.consultationsThisWeek": "cette semaine",
    "dashboard.kpi.chunks": "Base légale indexée",
    "dashboard.kpi.chunksHint": "passages du corpus tunisien",
    "dashboard.kpi.entities": "Entités du graphe",
    "dashboard.kpi.entitiesHint": "connectées dans Neo4j",
    "dashboard.kpi.clients": "Clients actifs",
    "dashboard.kpi.clientsHint": "Dossiers uniques suivis",
    "dashboard.activity": "Activité",
    "dashboard.last7days": "7 derniers jours",
    "dashboard.kb": "Base de connaissances",
    "dashboard.recent": "Consultations récentes",
    "dashboard.seeAll": "Tout voir",
    "dashboard.noConsultations": "Aucune consultation",
    "dashboard.noConsultationsHint": "Générez votre premier mémo fiscal.",
    "dashboard.createConsultation": "Créer une consultation",
    "dashboard.quickActions": "Actions rapides",
    "dashboard.qa.search": "Rechercher dans la loi",
    "dashboard.qa.searchDesc": "Codes, conventions & doctrine",
    "dashboard.qa.chat": "Interroger l'assistant",
    "dashboard.qa.chatDesc": "Réponses sourcées instantanées",
    "dashboard.qa.newConsultation": "Nouvelle consultation",
    "dashboard.qa.newConsultationDesc": "Mémo structuré en ~1 minute",
    "dashboard.qa.users": "Gérer les utilisateurs",
    "dashboard.qa.usersDesc": "Rôles, accès & activité",

    // JORT
    "jort.title": "Journal Officiel (JORT)",
    "jort.seeAll": "Voir tout",
    "jort.new": "Nouveau",

    // Chat bubble
    "chat.title": "Assistant fiscal",
    "chat.subtitle": "Réponses sourcées sur le corpus",
    "chat.placeholder": "Question fiscale rapide…",
    "chat.intro": "Une question rapide ?",
    "chat.introHint": "Posez votre question sans quitter la page.",

    // Chat page
    "chat.newChat": "Nouveau chat",
    "chat.hideHistory": "Masquer l'historique",
    "chat.showHistory": "Afficher l'historique",
    "chat.conversationHistory": "Historique des conversations",
    "chat.noConversations": "Aucune conversation",
    "chat.noConversationsHint":
      "Vos échanges avec l'assistant apparaîtront ici.",
    "chat.today": "Aujourd'hui",
    "chat.yesterday": "Hier",
    "chat.last7days": "7 derniers jours",
    "chat.last30days": "30 derniers jours",
    "chat.older": "Plus ancien",
    "chat.justNow": "à l'instant",
    "chat.minutesAgo": "il y a {n} min",
    "chat.hoursAgo": "il y a {n} h",
    "chat.exchange": "échange",
    "chat.exchanges": "échanges",
    "chat.confirmDelete": "Confirmer la suppression",
    "chat.deleteConversation": "Supprimer la conversation",
    "chat.clickToConfirm": "Cliquez pour confirmer",
    "chat.greeting": "une question fiscale ?",
    "chat.greetingDesc":
      "Chaque réponse est fondée sur le corpus juridique tunisien — et cite ses sources, consultables en un clic.",
    "chat.inputPlaceholder": "Posez votre question fiscale…",
    "chat.analyzing": "Analyse de la question…",
    "chat.errorMsg":
      "Désolé — je n'ai pas pu répondre. Vérifiez que Neo4j et le LLM sont connectés.",
    "chat.disclaimer":
      "Réponses générées par IA à partir du corpus indexé — vérifiez les sources citées.",
    "chat.references": "Références",
    "chat.sources": "Sources",
    "chat.closeTab": "Fermer l'onglet",

    // Chat suggestions
    "chat.sug1.title": "Retenue à la source",
    "chat.sug1.q":
      "Quel est le taux de retenue à la source sur les honoraires versés à un non-résident ?",
    "chat.sug2.title": "TVA à l'export",
    "chat.sug2.q":
      "La TVA est-elle due sur les prestations de services rendues à une société étrangère ?",
    "chat.sug3.title": "Prix de transfert",
    "chat.sug3.q":
      "Comment fonctionne le régime des prix de transfert en Tunisie ?",
    "chat.sug4.title": "Convention fiscale",
    "chat.sug4.q":
      "Comment la convention Tunisie-France traite-t-elle les dividendes ?",

    // Search page
    "search.lawTab": "Textes de loi",
    "search.consultationsTab": "Consultations",
    "search.filters": "Filtres",
    "search.clearAll": "Tout effacer",
    "search.textType": "Type de texte",
    "search.period": "Période",
    "search.from": "De",
    "search.to": "À",
    "search.client": "Client",
    "search.searchClient": "Rechercher un client…",
    "search.creationDate": "Date de création",
    "search.fromDate": "Du",
    "search.toDate": "Au",
    "search.country": "Pays",
    "search.keywords": "Mots-clés",
    "search.recent": "Récentes",
    "search.searchLaw": "Rechercher dans les textes de loi…",
    "search.searchConsultations": "Rechercher dans les consultations…",
    "search.searchBtn": "Rechercher",
    "search.results": "résultats",
    "search.consultation": "consultation",
    "search.consultations": "consultations",
    "search.whatLooking": "Que cherchez-vous ?",
    "search.lawHint": "Recherche sémantique sur 67 000+ passages juridiques.",
    "search.consHint": "Retrouvez un mémo par client, référence ou mots-clés.",
    "search.noLawResults": "Aucun texte trouvé",
    "search.noLawHint":
      "Élargissez les mots-clés ou réinitialisez les filtres.",
    "search.noConsResults": "Aucune consultation",
    "search.noConsHint": "Essayez un autre nom de client ou une référence.",
    "search.all": "Tous",
    "search.codes": "Codes",
    "search.conventions": "Conventions",
    "search.loisFinances": "Lois de finances",
    "search.doctrine": "Doctrine",
    "search.commentaires": "Commentaires",
    "search.searchFailed": "La recherche a échoué — vérifiez la connexion du moteur.",

    // Consultations page
    "cons.newConsultation": "Nouvelle consultation",
    "cons.memosGenerated": "mémo{s} généré{s}",
    "cons.describeCase": "Décrivez le dossier.",
    "cons.describeHint":
      "L'IA rédige un mémo structuré et sourcé sur le corpus juridique — en une minute environ.",
    "cons.theCase": "Le dossier",
    "cons.clientName": "Nom du client",
    "cons.clientPlaceholder": "Société X",
    "cons.reference": "Référence",
    "cons.optional": "optionnel",
    "cons.theSituation": "La situation",
    "cons.factualContext": "Contexte factuel",
    "cons.situationPlaceholder":
      "Qui sont les parties, quelles opérations, quels montants, quels pays…",
    "cons.characters": "caractères",
    "cons.min20": "min. 20",
    "cons.theQuestion": "La question",
    "cons.fiscalQuestion": "Question fiscale à trancher",
    "cons.questionPlaceholder": "Quelle est la question fiscale à traiter ?",
    "cons.min10": "min. 10",
    "cons.consultationFormat": "Format de la consultation",
    "cons.detailed": "Version détaillée",
    "cons.detailedDesc":
      "Principe, application aux faits et conclusion pour chaque point.",
    "cons.concise": "Version concise",
    "cons.conciseDesc":
      "Droit au but : le verdict et sa source, sans développement.",
    "cons.generate": "Générer la consultation",
    "cons.fillFields":
      "Renseignez le client, la situation et la question pour lancer la génération.",
    "cons.generating": "Rédaction de la consultation",
    "cons.generatingHint": "Généralement moins d'une minute.",
    "cons.memoPreview": "Aperçu du mémo",
    "cons.includeTips": "À inclure si possible",
    "cons.generated": "Consultation générée.",
    "cons.generateFailed": "La génération a échoué. Vérifiez le statut du moteur — Neo4j et le LLM doivent être connectés.",
    "cons.confirmLeave": "Génération en cours — quitter cette page ?",
    "cons.confirmDiscard": "Le brouillon en cours sera perdu — continuer ?",
    "cons.hideList": "Masquer la liste",
    "cons.showList": "Afficher la liste",
    "cons.previousConsultations": "Consultations précédentes",
    "cons.memos": "mémo",
    "cons.pipeline1": "Détection des branches & de la juridiction",
    "cons.pipeline1d": "IS · IRPP · TVA · Retenue · Prix de transfert",
    "cons.pipeline2": "Recherche sémantique du corpus",
    "cons.pipeline2d": "Embeddings multilingues sur 67k passages",
    "cons.pipeline3": "Récupération des sources (Neo4j)",
    "cons.pipeline3d": "Conventions → codes → lois de finances → doctrine",
    "cons.pipeline4": "Rédaction du contexte, étendue & sommaire",
    "cons.pipeline4d": "Phase 1",
    "cons.pipeline5": "Analyses & tableau de synthèse",
    "cons.pipeline5d": "Phases 2 ‖ 3 — en parallèle",
    "cons.pipeline6": "Résolution des citations & finalisation",
    "cons.pipeline6d": "Chaque affirmation tracée à sa source",
    "cons.tip1": "Forme juridique et résidence fiscale des parties",
    "cons.tip2": "Nature et montants des opérations concernées",
    "cons.tip3": "Pays impliqués si le dossier est international",
    "cons.tip4": "Dates et exercices fiscaux concernés",
    "cons.example1": "Quel est le traitement fiscal de ces redevances versées au prestataire français ?",
    "cons.example2": "La société bénéficie-t-elle d'un avantage fiscal au titre de cet investissement ?",
    "cons.example3": "Quelles obligations de retenue à la source s'appliquent ?",
    "cons.previewContext": "Contexte & faits",
    "cons.previewScope": "Étendue des travaux",
    "cons.previewSummary": "Sommaire exécutif",
    "cons.previewAnalysis": "Analyses",
    "cons.previewDocs": "Documents & références",
    "cons.previewFooter": "+ tableau de synthèse et sources juridiques numérotées, le tout modifiable avec l'IA après génération.",

    // Settings page
    "settings.title": "Paramètres",
    "settings.profile": "Profil",
    "settings.security": "Sécurité",
    "settings.changePassword": "Changer le mot de passe",
    "settings.secureAccount": "Sécurisez votre compte",
    "settings.activeSessions": "Sessions actives",
    "settings.logoutAll": "Tout déconnecter",
    "settings.loading": "Chargement…",
    "settings.noSessions": "Aucune session active.",
    "settings.thisDevice": "Cet appareil",
    "settings.unknownIP": "IP inconnue",
    "settings.revoke": "Révoquer",
    "settings.account": "Compte",
    "settings.logout": "Se déconnecter",
    "settings.lastLogin": "Dernière connexion",

    // Admin Users
    "admin.users.title": "Utilisateurs",
    "admin.users.subtitle": "Gérez les rôles, accès et activité.",
    "admin.users.search": "Rechercher…",
    "admin.users.searchBtn": "Rechercher",
    "admin.users.name": "Nom",
    "admin.users.email": "Email",
    "admin.users.role": "Rôle",
    "admin.users.status": "Statut",
    "admin.users.actions": "Actions",
    "admin.users.active": "Actif",
    "admin.users.locked": "Verrouillé",
    "admin.users.lock": "Verrouiller",
    "admin.users.unlock": "Déverrouiller",
    "admin.users.promote": "Promouvoir Admin",
    "admin.users.demote": "Rétrograder User",
    "admin.users.activity": "Activité",
    "admin.users.hide": "Masquer",
    "admin.users.previous": "Précédent",
    "admin.users.next": "Suivant",
    "admin.users.page": "Page",
    "admin.users.of": "sur",
    "admin.users.loading": "Chargement…",
    "admin.users.noUsers": "Aucun utilisateur trouvé.",
    "admin.users.you": "vous",
    "admin.users.lastLogin": "Dernière connexion",
    "admin.users.recentActivity": "Activité récente",
    "admin.users.noActivity": "Aucune activité enregistrée.",
    "admin.users.usersLabel": "utilisateurs",
    "admin.users.user": "Utilisateur",

    // System Status
    "system.checking": "Vérification…",
    "system.allOnline": "Tout en ligne",
    "system.issue": "Problème",
    "system.api": "API .NET",
    "system.neo4j": "Neo4j",
    "system.elastic": "Elasticsearch",
    "system.embed": "Embeddings",
    "system.connected": "Connecté",
    "system.setupNeeded": "Configuration requise",
    "system.engineStatus": "Statut du moteur",
    "system.knowledgeBase": "Base de connaissances (Neo4j)",
    "system.aiModel": "Modèle IA (LLM)",
    "system.embedServer": "Serveur d'embeddings",
    "system.chunksIndexed": "{n} passages indexés",
    "system.configured": "Configuré",
    "system.neo4jHint": "Définissez Neo4j:Password dans appsettings.Development.json et redémarrez l'API.",
    "system.llmHint": "Ajoutez une clé OpenAI:ApiKey valide dans appsettings.Development.json.",
    "system.embedRunning": "En cours sur :8081",
    "system.embedHint": "Optionnel — lancez ./start-embed-server.sh pour la recherche vectorielle.",

    // Editor
    "editor.aiCoWriter": "Co-rédacteur IA",
    "editor.aiCoWriterHint": "Modifiez le document en langage naturel",
    "editor.hidePanel": "Masquer le panneau",
    "editor.target": "Cible",
    "editor.modifyNaturalLanguage": "Modifiez le document en langage naturel.",
    "editor.selectPassage": "Sélectionnez un passage dans le document, ou ciblez une section et décrivez le changement :",
    "editor.example1": "Ajoute une analyse sur la TVA pour les non-résidents.",
    "editor.example2": "Reformule le sommaire de façon plus concise.",
    "editor.example3": "Cite la convention Tunisie-France sur les dividendes.",
    "editor.rewriting": "Réécriture",
    "editor.modify": "Modifier",
    "editor.refineFailed": "La modification a échoué. Vérifiez que le LLM est connecté.",
    "editor.saved": "Enregistré",
    "editor.save": "Enregistrer",
    "editor.saveFailed": "Échec de l'enregistrement.",
    "editor.exportSuccess": "Document Word exporté.",
    "editor.exportFailed": "Échec de l'export.",
    "editor.rated": "Noté",
    "editor.rate": "Noter",
    "editor.unsavedWarning": "Modifications non enregistrées — changer de document quand même ?",
    "editor.unsaved": "Modifications non enregistrées",
    "editor.hideList": "Masquer la liste",
    "editor.showList": "Afficher la liste",
    "editor.allConsultations": "Toutes les consultations",
    "editor.opening": "Ouverture du document…",
    "editor.aiAssistant": "Assistant IA",
    "editor.expertise": "Expertise comptable & conseil fiscal",
    "editor.fiscalConsultation": "Avis de consultation fiscale",
    "editor.consultationSubtitle": "Note de conseil — Situation fiscale",
    "editor.reference": "Référence",
    "editor.date": "Date",
    "editor.recipient": "Destinataire",
    "editor.author": "Rédacteur",
    "editor.subject": "Sujet",
    "editor.analysis": "Analyse",
    "editor.conclusion": "Conclusion",
    "editor.legalSources": "Sources juridiques",
    "editor.confidential": "Document confidentiel — Ne pas diffuser",
    "editor.modifyWith": "Modifier avec l'IA",
    "editor.selectedPassage": "Passage sélectionné",
    "editor.describeModification": "Ou décrivez la modification…",
  },
  en: {
    // Sidebar
    "sidebar.workspace": "Workspace",
    "sidebar.dashboard": "Dashboard",
    "sidebar.search": "Search",
    "sidebar.chat": "AI Assistant",
    "sidebar.consultations": "Consultations",
    "sidebar.admin": "Administration",
    "sidebar.users": "Users",
    "sidebar.settings": "Settings",

    // Dashboard
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.subtitle":
      "Your tax copilot — research, advice and sourced consultations.",
    "dashboard.askQuestion": "Ask a question",
    "dashboard.newConsultation": "New consultation",
    "dashboard.kpi.consultations": "Consultations",
    "dashboard.kpi.consultationsHint": "total",
    "dashboard.kpi.consultationsThisWeek": "this week",
    "dashboard.kpi.chunks": "Indexed legal base",
    "dashboard.kpi.chunksHint": "passages in the Tunisian corpus",
    "dashboard.kpi.entities": "Graph entities",
    "dashboard.kpi.entitiesHint": "connected in Neo4j",
    "dashboard.kpi.clients": "Active clients",
    "dashboard.kpi.clientsHint": "Unique client files",
    "dashboard.activity": "Activity",
    "dashboard.last7days": "last 7 days",
    "dashboard.kb": "Knowledge base",
    "dashboard.recent": "Recent consultations",
    "dashboard.seeAll": "See all",
    "dashboard.noConsultations": "No consultations",
    "dashboard.noConsultationsHint": "Generate your first tax memo.",
    "dashboard.createConsultation": "Create a consultation",
    "dashboard.quickActions": "Quick actions",
    "dashboard.qa.search": "Search the law",
    "dashboard.qa.searchDesc": "Codes, treaties & doctrine",
    "dashboard.qa.chat": "Ask the assistant",
    "dashboard.qa.chatDesc": "Instant sourced answers",
    "dashboard.qa.newConsultation": "New consultation",
    "dashboard.qa.newConsultationDesc": "Structured memo in ~1 minute",
    "dashboard.qa.users": "Manage users",
    "dashboard.qa.usersDesc": "Roles, access & activity",

    // JORT
    "jort.title": "Official Gazette (JORT)",
    "jort.seeAll": "See all",
    "jort.new": "New",

    // Chat bubble
    "chat.title": "Tax assistant",
    "chat.subtitle": "Answers sourced from the corpus",
    "chat.placeholder": "Quick tax question…",
    "chat.intro": "A quick question?",
    "chat.introHint": "Ask without leaving the page.",

    // Chat page
    "chat.newChat": "New chat",
    "chat.hideHistory": "Hide history",
    "chat.showHistory": "Show history",
    "chat.conversationHistory": "Conversation history",
    "chat.noConversations": "No conversations",
    "chat.noConversationsHint":
      "Your exchanges with the assistant will appear here.",
    "chat.today": "Today",
    "chat.yesterday": "Yesterday",
    "chat.last7days": "Last 7 days",
    "chat.last30days": "Last 30 days",
    "chat.older": "Older",
    "chat.justNow": "just now",
    "chat.minutesAgo": "{n} min ago",
    "chat.hoursAgo": "{n}h ago",
    "chat.exchange": "exchange",
    "chat.exchanges": "exchanges",
    "chat.confirmDelete": "Confirm deletion",
    "chat.deleteConversation": "Delete conversation",
    "chat.clickToConfirm": "Click to confirm",
    "chat.greeting": "a tax question?",
    "chat.greetingDesc":
      "Every answer is grounded in the Tunisian legal corpus — with clickable cited sources.",
    "chat.inputPlaceholder": "Ask your tax question…",
    "chat.analyzing": "Analyzing question…",
    "chat.errorMsg":
      "Sorry — I couldn't answer. Check that Neo4j and the LLM are connected.",
    "chat.disclaimer":
      "AI-generated answers from the indexed corpus — verify the cited sources.",
    "chat.references": "References",
    "chat.sources": "Sources",
    "chat.closeTab": "Close tab",

    // Chat suggestions
    "chat.sug1.title": "Withholding tax",
    "chat.sug1.q":
      "What is the withholding tax rate on fees paid to a non-resident?",
    "chat.sug2.title": "Export VAT",
    "chat.sug2.q": "Is VAT due on services rendered to a foreign company?",
    "chat.sug3.title": "Transfer pricing",
    "chat.sug3.q": "How does the transfer pricing regime work in Tunisia?",
    "chat.sug4.title": "Tax treaty",
    "chat.sug4.q": "How does the Tunisia-France treaty handle dividends?",

    // Search page
    "search.lawTab": "Legal texts",
    "search.consultationsTab": "Consultations",
    "search.filters": "Filters",
    "search.clearAll": "Clear all",
    "search.textType": "Text type",
    "search.period": "Period",
    "search.from": "From",
    "search.to": "To",
    "search.client": "Client",
    "search.searchClient": "Search a client…",
    "search.creationDate": "Creation date",
    "search.fromDate": "From",
    "search.toDate": "To",
    "search.country": "Country",
    "search.keywords": "Keywords",
    "search.recent": "Recent",
    "search.searchLaw": "Search legal texts…",
    "search.searchConsultations": "Search consultations…",
    "search.searchBtn": "Search",
    "search.results": "results",
    "search.consultation": "consultation",
    "search.consultations": "consultations",
    "search.whatLooking": "What are you looking for?",
    "search.lawHint": "Semantic search across 67,000+ legal passages.",
    "search.consHint": "Find a memo by client, reference, or keywords.",
    "search.noLawResults": "No texts found",
    "search.noLawHint": "Broaden your keywords or reset the filters.",
    "search.noConsResults": "No consultations",
    "search.noConsHint": "Try a different client name or reference.",
    "search.all": "All",
    "search.codes": "Codes",
    "search.conventions": "Conventions",
    "search.loisFinances": "Finance laws",
    "search.doctrine": "Doctrine",
    "search.commentaires": "Comments",
    "search.searchFailed": "Search failed — check the engine connection.",

    // Consultations page
    "cons.newConsultation": "New consultation",
    "cons.memosGenerated": "memo{s} generated",
    "cons.describeCase": "Describe the case.",
    "cons.describeHint":
      "AI drafts a structured and sourced memo from the legal corpus — in about one minute.",
    "cons.theCase": "The case",
    "cons.clientName": "Client name",
    "cons.clientPlaceholder": "Company X",
    "cons.reference": "Reference",
    "cons.optional": "optional",
    "cons.theSituation": "The situation",
    "cons.factualContext": "Factual context",
    "cons.situationPlaceholder":
      "Who are the parties, what operations, what amounts, what countries…",
    "cons.characters": "characters",
    "cons.min20": "min. 20",
    "cons.theQuestion": "The question",
    "cons.fiscalQuestion": "Tax question to resolve",
    "cons.questionPlaceholder": "What is the tax question to address?",
    "cons.min10": "min. 10",
    "cons.consultationFormat": "Consultation format",
    "cons.detailed": "Detailed version",
    "cons.detailedDesc":
      "Principle, application to the facts, and conclusion for each point.",
    "cons.concise": "Concise version",
    "cons.conciseDesc":
      "Straight to the point: the verdict and its source, no elaboration.",
    "cons.generate": "Generate consultation",
    "cons.fillFields":
      "Fill in the client, situation, and question to start generation.",
    "cons.generating": "Drafting the consultation",
    "cons.generatingHint": "Usually less than a minute.",
    "cons.memoPreview": "Memo preview",
    "cons.includeTips": "Include if possible",
    "cons.generated": "Consultation generated.",
    "cons.generateFailed": "Generation failed. Check the engine status — Neo4j and the LLM must be connected.",
    "cons.confirmLeave": "Generation in progress — leave this page?",
    "cons.confirmDiscard": "The current draft will be lost — continue?",
    "cons.hideList": "Hide list",
    "cons.showList": "Show list",
    "cons.previousConsultations": "Previous consultations",
    "cons.memos": "memo",
    "cons.pipeline1": "Detecting branches & jurisdiction",
    "cons.pipeline1d": "CIT · PIT · VAT · Withholding · Transfer pricing",
    "cons.pipeline2": "Semantic corpus search",
    "cons.pipeline2d": "Multilingual embeddings on 67k passages",
    "cons.pipeline3": "Source retrieval (Neo4j)",
    "cons.pipeline3d": "Treaties → codes → finance laws → doctrine",
    "cons.pipeline4": "Drafting context, scope & summary",
    "cons.pipeline4d": "Phase 1",
    "cons.pipeline5": "Analysis & summary table",
    "cons.pipeline5d": "Phases 2 ‖ 3 — in parallel",
    "cons.pipeline6": "Citation resolution & finalization",
    "cons.pipeline6d": "Every assertion traced to its source",
    "cons.tip1": "Legal form and tax residency of the parties",
    "cons.tip2": "Nature and amounts of the operations involved",
    "cons.tip3": "Countries involved if the case is international",
    "cons.tip4": "Dates and fiscal years concerned",
    "cons.example1": "What is the tax treatment of these royalties paid to the French provider?",
    "cons.example2": "Does the company benefit from a tax incentive for this investment?",
    "cons.example3": "What withholding tax obligations apply?",
    "cons.previewContext": "Context & facts",
    "cons.previewScope": "Scope of work",
    "cons.previewSummary": "Executive summary",
    "cons.previewAnalysis": "Analysis",
    "cons.previewDocs": "Documents & references",
    "cons.previewFooter": "+ summary table and numbered legal sources, all editable with AI after generation.",

    // Settings page
    "settings.title": "Settings",
    "settings.profile": "Profile",
    "settings.security": "Security",
    "settings.changePassword": "Change password",
    "settings.secureAccount": "Secure your account",
    "settings.activeSessions": "Active sessions",
    "settings.logoutAll": "Sign out everywhere",
    "settings.loading": "Loading…",
    "settings.noSessions": "No active sessions.",
    "settings.thisDevice": "This device",
    "settings.unknownIP": "Unknown IP",
    "settings.revoke": "Revoke",
    "settings.account": "Account",
    "settings.logout": "Sign out",
    "settings.lastLogin": "Last login",

    // Admin Users
    "admin.users.title": "Users",
    "admin.users.subtitle": "Manage roles, access, and activity.",
    "admin.users.search": "Search…",
    "admin.users.searchBtn": "Search",
    "admin.users.name": "Name",
    "admin.users.email": "Email",
    "admin.users.role": "Role",
    "admin.users.status": "Status",
    "admin.users.actions": "Actions",
    "admin.users.active": "Active",
    "admin.users.locked": "Locked",
    "admin.users.lock": "Lock",
    "admin.users.unlock": "Unlock",
    "admin.users.promote": "Promote to Admin",
    "admin.users.demote": "Demote to User",
    "admin.users.activity": "Activity",
    "admin.users.hide": "Hide",
    "admin.users.previous": "Previous",
    "admin.users.next": "Next",
    "admin.users.page": "Page",
    "admin.users.of": "of",
    "admin.users.loading": "Loading…",
    "admin.users.noUsers": "No users found.",
    "admin.users.you": "you",
    "admin.users.lastLogin": "Last login",
    "admin.users.recentActivity": "Recent activity",
    "admin.users.noActivity": "No activity recorded.",
    "admin.users.usersLabel": "users",
    "admin.users.user": "User",

    // System Status
    "system.checking": "Checking…",
    "system.allOnline": "All online",
    "system.issue": "Issue",
    "system.api": ".NET API",
    "system.neo4j": "Neo4j",
    "system.elastic": "Elasticsearch",
    "system.embed": "Embeddings",
    "system.connected": "Connected",
    "system.setupNeeded": "Setup needed",
    "system.engineStatus": "Engine status",
    "system.knowledgeBase": "Knowledge base (Neo4j)",
    "system.aiModel": "AI model (LLM)",
    "system.embedServer": "Embedding server",
    "system.chunksIndexed": "{n} chunks indexed",
    "system.configured": "Configured",
    "system.neo4jHint": "Set Neo4j:Password in appsettings.Development.json and restart the API.",
    "system.llmHint": "Add a valid OpenAI:ApiKey in appsettings.Development.json.",
    "system.embedRunning": "Running on :8081",
    "system.embedHint": "Optional — run ./start-embed-server.sh for vector search.",

    // Editor
    "editor.aiCoWriter": "AI Co-writer",
    "editor.aiCoWriterHint": "Edit the document in natural language",
    "editor.hidePanel": "Hide panel",
    "editor.target": "Target",
    "editor.modifyNaturalLanguage": "Edit the document in natural language.",
    "editor.selectPassage": "Select a passage in the document, or target a section and describe the change:",
    "editor.example1": "Add a VAT analysis for non-residents.",
    "editor.example2": "Rephrase the summary more concisely.",
    "editor.example3": "Cite the Tunisia-France convention on dividends.",
    "editor.rewriting": "Rewriting",
    "editor.modify": "Edit",
    "editor.refineFailed": "The modification failed. Check that the LLM is connected.",
    "editor.saved": "Saved",
    "editor.save": "Save",
    "editor.saveFailed": "Save failed.",
    "editor.exportSuccess": "Word document exported.",
    "editor.exportFailed": "Export failed.",
    "editor.rated": "Rated",
    "editor.rate": "Rate",
    "editor.unsavedWarning": "Unsaved changes — switch document anyway?",
    "editor.unsaved": "Unsaved changes",
    "editor.hideList": "Hide list",
    "editor.showList": "Show list",
    "editor.allConsultations": "All consultations",
    "editor.opening": "Opening document…",
    "editor.aiAssistant": "AI Assistant",
    "editor.expertise": "Accounting expertise & tax advisory",
    "editor.fiscalConsultation": "Tax consultation notice",
    "editor.consultationSubtitle": "Advisory note — Tax situation",
    "editor.reference": "Reference",
    "editor.date": "Date",
    "editor.recipient": "Recipient",
    "editor.author": "Author",
    "editor.subject": "Subject",
    "editor.analysis": "Analysis",
    "editor.conclusion": "Conclusion",
    "editor.legalSources": "Legal sources",
    "editor.confidential": "Confidential document — Do not distribute",
    "editor.modifyWith": "Edit with AI",
    "editor.selectedPassage": "Selected passage",
    "editor.describeModification": "Or describe the modification…",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem("taxmind.lang") || "fr",
  );

  useEffect(() => {
    localStorage.setItem("taxmind.lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key, params) => {
    let str = STRINGS[lang]?.[key] ?? STRINGS.fr[key] ?? key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
