import { createContext, useContext, useEffect, useState } from "react";

const STRINGS = {
  fr: {
    // Sidebar
    "sidebar.workspace": "Workspace",
    "sidebar.dashboard": "Dashboard",
    "sidebar.search": "Recherche",
    "sidebar.chat": "Assistant IA",
    "sidebar.consultations": "Consultations",
    "sidebar.admin": "Administration",
    "sidebar.users": "Utilisateurs",
    "sidebar.settings": "Paramètres",

    // Dashboard
    "dashboard.greeting.morning": "Bonjour",
    "dashboard.greeting.afternoon": "Bon après-midi",
    "dashboard.greeting.evening": "Bonsoir",
    "dashboard.subtitle":
      "Votre copilote fiscal — recherche, conseil et consultations.",
    "dashboard.askQuestion": "Poser une question",
    "dashboard.newConsultation": "Nouvelle consultation",
    "dashboard.kpi.consultations": "Consultations",
    "dashboard.kpi.consultationsHint": "au total",
    "dashboard.kpi.consultationsThisWeek": "cette semaine",
    "dashboard.kpi.chunks": "Base légale indexée",
    "dashboard.kpi.chunksHint": "passages du corpus tunisien",
    "dashboard.kpi.entities": "Entités du graphe",
    "dashboard.kpi.entitiesHint": "connectées dans Neo4j",
    "dashboard.kpi.clients": "Clients actifs",
    "dashboard.kpi.clientsHint": "Dossiers uniques suivis",
    "dashboard.activity": "Activité",
    "dashboard.last7days": "7 derniers jours",
    "dashboard.kb": "Base de connaissances",
    "dashboard.recent": "Consultations récentes",
    "dashboard.seeAll": "Tout voir",
    "dashboard.noConsultations": "Aucune consultation",
    "dashboard.noConsultationsHint": "Générez votre premier mémo fiscal.",
    "dashboard.createConsultation": "Créer une consultation",
    "dashboard.quickActions": "Actions rapides",
    "dashboard.qa.search": "Rechercher dans la loi",
    "dashboard.qa.searchDesc": "Codes, conventions & doctrine",
    "dashboard.qa.chat": "Interroger l'assistant",
    "dashboard.qa.chatDesc": "Réponses sourcées instantanées",
    "dashboard.qa.newConsultation": "Nouvelle consultation",
    "dashboard.qa.newConsultationDesc": "Mémo structuré en ~1 minute",
    "dashboard.qa.users": "Gérer les utilisateurs",
    "dashboard.qa.usersDesc": "Rôles, accès & activité",

    // JORT
    "jort.title": "Journal Officiel (JORT)",
    "jort.seeAll": "Voir tout",
    "jort.new": "Nouveau",

    // Chat bubble
    "chat.title": "Assistant fiscal",
    "chat.subtitle": "Réponses sourcées sur le corpus",
    "chat.placeholder": "Question fiscale rapide…",
    "chat.intro": "Une question rapide ?",
    "chat.introHint": "Posez votre question sans quitter la page.",

    // Chat page
    "chat.newChat": "Nouveau chat",
    "chat.hideHistory": "Masquer l'historique",
    "chat.showHistory": "Afficher l'historique",
    "chat.conversationHistory": "Historique des conversations",
    "chat.noConversations": "Aucune conversation",
    "chat.noConversationsHint":
      "Vos échanges avec l'assistant apparaîtront ici.",
    "chat.today": "Aujourd'hui",
    "chat.yesterday": "Hier",
    "chat.last7days": "7 derniers jours",
    "chat.last30days": "30 derniers jours",
    "chat.older": "Plus ancien",
    "chat.justNow": "à l'instant",
    "chat.minutesAgo": "il y a {n} min",
    "chat.hoursAgo": "il y a {n} h",
    "chat.exchange": "échange",
    "chat.exchanges": "échanges",
    "chat.confirmDelete": "Confirmer la suppression",
    "chat.deleteConversation": "Supprimer la conversation",
    "chat.clickToConfirm": "Cliquez pour confirmer",
    "chat.greeting": "une question fiscale ?",
    "chat.greetingDesc":
      "Chaque réponse est fondée sur le corpus juridique tunisien — et cite ses sources, consultables en un clic.",
    "chat.inputPlaceholder": "Posez votre question fiscale…",
    "chat.analyzing": "Analyse de la question…",
    "chat.errorMsg":
      "Désolé — je n'ai pas pu répondre. Vérifiez que Neo4j et le LLM sont connectés.",
    "chat.disclaimer":
      "Réponses générées par IA à partir du corpus indexé — vérifiez les sources citées.",
    "chat.references": "Références",
    "chat.sources": "Sources",
    "chat.closeTab": "Fermer l'onglet",

    // Chat suggestions
    "chat.sug1.title": "Retenue à la source",
    "chat.sug1.q":
      "Quel est le taux de retenue à la source sur les honoraires versés à un non-résident ?",
    "chat.sug2.title": "TVA à l'export",
    "chat.sug2.q":
      "La TVA est-elle due sur les prestations de services rendues à une société étrangère ?",
    "chat.sug3.title": "Prix de transfert",
    "chat.sug3.q":
      "Comment fonctionne le régime des prix de transfert en Tunisie ?",
    "chat.sug4.title": "Convention fiscale",
    "chat.sug4.q":
      "Comment la convention Tunisie-France traite-t-elle les dividendes ?",

    // Search page
    "search.lawTab": "Textes de loi",
    "search.consultationsTab": "Consultations",
    "search.filters": "Filtres",
    "search.clearAll": "Tout effacer",
    "search.textType": "Type de texte",
    "search.period": "Période",
    "search.from": "De",
    "search.to": "À",
    "search.client": "Client",
    "search.searchClient": "Rechercher un client…",
    "search.creationDate": "Date de création",
    "search.fromDate": "Du",
    "search.toDate": "Au",
    "search.country": "Pays",
    "search.keywords": "Mots-clés",
    "search.recent": "Récentes",
    "search.searchLaw": "Rechercher dans les textes de loi…",
    "search.searchConsultations": "Rechercher dans les consultations…",
    "search.searchBtn": "Rechercher",
    "search.results": "résultats",
    "search.consultation": "consultation",
    "search.consultations": "consultations",
    "search.whatLooking": "Que cherchez-vous ?",
    "search.lawHint": "Recherche sémantique sur 67 000+ passages juridiques.",
    "search.consHint": "Retrouvez un mémo par client, référence ou mots-clés.",
    "search.noLawResults": "Aucun texte trouvé",
    "search.noLawHint":
      "Élargissez les mots-clés ou réinitialisez les filtres.",
    "search.noConsResults": "Aucune consultation",
    "search.noConsHint": "Essayez un autre nom de client ou une référence.",
    "search.all": "Tous",
    "search.codes": "Codes",
    "search.conventions": "Conventions",
    "search.loisFinances": "Lois de finances",
    "search.doctrine": "Doctrine",
    "search.commentaires": "Commentaires",
    "search.searchFailed": "La recherche a échoué — vérifiez la connexion du moteur.",

    // Consultations page
    "cons.newConsultation": "Nouvelle consultation",
    "cons.memosGenerated": "mémo{s} généré{s}",
    "cons.describeCase": "Décrivez le dossier.",
    "cons.describeHint":
      "L'IA rédige un mémo structuré et sourcé sur le corpus juridique — en une minute environ.",
    "cons.theCase": "Le dossier",
    "cons.clientName": "Nom du client",
    "cons.clientPlaceholder": "Société X",
    "cons.reference": "Référence",
    "cons.optional": "optionnel",
    "cons.theSituation": "La situation",
    "cons.factualContext": "Contexte factuel",
    "cons.situationPlaceholder":
      "Qui sont les parties, quelles opérations, quels montants, quels pays…",
    "cons.characters": "caractères",
    "cons.min20": "min. 20",
    "cons.theQuestion": "La question",
    "cons.fiscalQuestion": "Question fiscale à trancher",
    "cons.questionPlaceholder": "Quelle est la question fiscale à traiter ?",
    "cons.min10": "min. 10",
    "cons.consultationFormat": "Format de la consultation",
    "cons.detailed": "Version détaillée",
    "cons.detailedDesc":
      "Principe, application aux faits et conclusion pour chaque point.",
    "cons.concise": "Version concise",
    "cons.conciseDesc":
      "Droit au but : le verdict et sa source, sans développement.",
    "cons.generate": "Générer la consultation",
    "cons.fillFields":
      "Renseignez le client, la situation et la question pour lancer la génération.",
    "cons.generating": "Rédaction de la consultation",
    "cons.generatingHint": "Généralement moins d'une minute.",
    "cons.memoPreview": "Aperçu du mémo",
    "cons.includeTips": "À inclure si possible",
    "cons.generated": "Consultation générée.",
    "cons.generateFailed": "La génération a échoué. Vérifiez le statut du moteur — Neo4j et le LLM doivent être connectés.",
    "cons.confirmLeave": "Génération en cours — quitter cette page ?",
    "cons.confirmDiscard": "Le brouillon en cours sera perdu — continuer ?",
    "cons.hideList": "Masquer la liste",
    "cons.showList": "Afficher la liste",
    "cons.previousConsultations": "Consultations précédentes",
    "cons.memos": "mémo",
    "cons.pipeline1": "Détection des branches & de la juridiction",
    "cons.pipeline1d": "IS · IRPP · TVA · Retenue · Prix de transfert",
    "cons.pipeline2": "Recherche sémantique du corpus",
    "cons.pipeline2d": "Embeddings multilingues sur 67k passages",
    "cons.pipeline3": "Récupération des sources (Neo4j)",
    "cons.pipeline3d": "Conventions → codes → lois de finances → doctrine",
    "cons.pipeline4": "Rédaction du contexte, étendue & sommaire",
    "cons.pipeline4d": "Phase 1",
    "cons.pipeline5": "Analyses & tableau de synthèse",
    "cons.pipeline5d": "Phases 2 ‖ 3 — en parallèle",
    "cons.pipeline6": "Résolution des citations & finalisation",
    "cons.pipeline6d": "Chaque affirmation tracée à sa source",
    "cons.tip1": "Forme juridique et résidence fiscale des parties",
    "cons.tip2": "Nature et montants des opérations concernées",
    "cons.tip3": "Pays impliqués si le dossier est international",
    "cons.tip4": "Dates et exercices fiscaux concernés",
    "cons.example1": "Quel est le traitement fiscal de ces redevances versées au prestataire français ?",
    "cons.example2": "La société bénéficie-t-elle d'un avantage fiscal au titre de cet investissement ?",
    "cons.example3": "Quelles obligations de retenue à la source s'appliquent ?",
    "cons.previewContext": "Contexte & faits",
    "cons.previewScope": "Étendue des travaux",
    "cons.previewSummary": "Sommaire exécutif",
    "cons.previewAnalysis": "Analyses",
    "cons.previewDocs": "Documents & références",
    "cons.previewFooter": "+ tableau de synthèse et sources juridiques numérotées, le tout modifiable avec l'IA après génération.",

    // Settings page
    "settings.title": "Paramètres",
    "settings.profile": "Profil",
    "settings.security": "Sécurité",
    "settings.changePassword": "Changer le mot de passe",
    "settings.secureAccount": "Sécurisez votre compte",
    "settings.activeSessions": "Sessions actives",
    "settings.logoutAll": "Tout déconnecter",
    "settings.loading": "Chargement…",
    "settings.noSessions": "Aucune session active.",
    "settings.thisDevice": "Cet appareil",
    "settings.unknownIP": "IP inconnue",
    "settings.revoke": "Révoquer",
    "settings.account": "Compte",
    "settings.logout": "Se déconnecter",
    "settings.lastLogin": "Dernière connexion",

    // Admin Users
    "admin.users.title": "Utilisateurs",
    "admin.users.subtitle": "Gérez les rôles, accès et activité.",
    "admin.users.search": "Rechercher…",
    "admin.users.searchBtn": "Rechercher",
    "admin.users.name": "Nom",
    "admin.users.email": "Email",
    "admin.users.role": "Rôle",
    "admin.users.status": "Statut",
    "admin.users.actions": "Actions",
    "admin.users.active": "Actif",
    "admin.users.locked": "Verrouillé",
    "admin.users.lock": "Verrouiller",
    "admin.users.unlock": "Déverrouiller",
    "admin.users.promote": "Promouvoir Admin",
    "admin.users.demote": "Rétrograder User",
    "admin.users.activity": "Activité",
    "admin.users.hide": "Masquer",
    "admin.users.previous": "Précédent",
    "admin.users.next": "Suivant",
    "admin.users.page": "Page",
    "admin.users.of": "sur",
    "admin.users.loading": "Chargement…",
    "admin.users.noUsers": "Aucun utilisateur trouvé.",
    "admin.users.you": "vous",
    "admin.users.lastLogin": "Dernière connexion",
    "admin.users.recentActivity": "Activité récente",
    "admin.users.noActivity": "Aucune activité enregistrée.",
    "admin.users.usersLabel": "utilisateurs",
    "admin.users.user": "Utilisateur",

    // System Status
    "system.checking": "Vérification…",
    "system.allOnline": "Tout en ligne",
    "system.issue": "Problème",
    "system.api": "API .NET",
    "system.neo4j": "Neo4j",
    "system.elastic": "Elasticsearch",
    "system.embed": "Embeddings",
    "system.connected": "Connecté",
    "system.setupNeeded": "Configuration requise",
    "system.engineStatus": "Statut du moteur",
    "system.knowledgeBase": "Base de connaissances (Neo4j)",
    "system.aiModel": "Modèle IA (LLM)",
    "system.embedServer": "Serveur d'embeddings",
    "system.chunksIndexed": "{n} passages indexés",
    "system.configured": "Configuré",
    "system.neo4jHint": "Définissez Neo4j:Password dans appsettings.Development.json et redémarrez l'API.",
    "system.llmHint": "Ajoutez une clé OpenAI:ApiKey valide dans appsettings.Development.json.",
    "system.embedRunning": "En cours sur :8081",
    "system.embedHint": "Optionnel — lancez ./start-embed-server.sh pour la recherche vectorielle.",

    // Editor
    "editor.aiCoWriter": "Co-rédacteur IA",
    "editor.aiCoWriterHint": "Modifiez le document en langage naturel",
    "editor.hidePanel": "Masquer le panneau",
    "editor.target": "Cible",
    "editor.modifyNaturalLanguage": "Modifiez le document en langage naturel.",
    "editor.selectPassage": "Sélectionnez un passage dans le document, ou ciblez une section et décrivez le changement :",
    "editor.example1": "Ajoute une analyse sur la TVA pour les non-résidents.",
    "editor.example2": "Reformule le sommaire de façon plus concise.",
    "editor.example3": "Cite la convention Tunisie-France sur les dividendes.",
    "editor.rewriting": "Réécriture",
    "editor.modify": "Modifier",
    "editor.refineFailed": "La modification a échoué. Vérifiez que le LLM est connecté.",
    "editor.saved": "Enregistré",
    "editor.save": "Enregistrer",
    "editor.saveFailed": "Échec de l'enregistrement.",
    "editor.exportSuccess": "Document Word exporté.",
    "editor.exportFailed": "Échec de l'export.",
    "editor.rated": "Noté",
    "editor.rate": "Noter",
    "editor.unsavedWarning": "Modifications non enregistrées — changer de document quand même ?",
    "editor.unsaved": "Modifications non enregistrées",
    "editor.hideList": "Masquer la liste",
    "editor.showList": "Afficher la liste",
    "editor.allConsultations": "Toutes les consultations",
    "editor.opening": "Ouverture du document…",
    "editor.aiAssistant": "Assistant IA",
    "editor.expertise": "Expertise comptable & conseil fiscal",
    "editor.fiscalConsultation": "Avis de consultation fiscale",
    "editor.consultationSubtitle": "Note de conseil — Situation fiscale",
    "editor.reference": "Référence",
    "editor.date": "Date",
    "editor.recipient": "Destinataire",
    "editor.author": "Rédacteur",
    "editor.subject": "Sujet",
    "editor.analysis": "Analyse",
    "editor.conclusion": "Conclusion",
    "editor.legalSources": "Sources juridiques",
    "editor.confidential": "Document confidentiel — Ne pas diffuser",
    "editor.modifyWith": "Modifier avec l'IA",
    "editor.selectedPassage": "Passage sélectionné",
    "editor.describeModification": "Ou décrivez la modification…",

    // Sidebar (rôles)
    "sidebar.tasks": "Mes tâches",
    "sidebar.management": "Management",
    "sidebar.consultants": "Consultants",
    "sidebar.adminOverview": "Vue d'ensemble",
    "sidebar.reclamations": "Réclamations",
    "sidebar.activity": "Activité",
    "sidebar.knowledge": "Base de connaissances",
    "sidebar.support": "Support",

    // Admin — vue d'ensemble
    "admin.overview.title": "Administration",
    "admin.overview.subtitle": "Pilotage de la plateforme — utilisateurs, rôles et gouvernance.",
    "admin.overview.addUser": "Ajouter un utilisateur",
    "admin.overview.reviewReclamations": "Réclamations",
    "admin.overview.kpi.users": "Utilisateurs",
    "admin.overview.kpi.thisMonth": "ce mois-ci",
    "admin.overview.kpi.reclamations": "Réclamations en attente",
    "admin.overview.kpi.resolved": "résolues",
    "admin.overview.kpi.consultations": "Consultations",
    "admin.overview.kpi.thisWeek": "cette semaine",
    "admin.overview.kpi.tasks": "Tâches en cours",
    "admin.overview.kpi.awaitingReview": "à valider",
    "admin.overview.roleDistribution": "Répartition des rôles",
    "admin.overview.locked": "verrouillé(s)",
    "admin.overview.recentUsers": "Dernières inscriptions",
    "admin.overview.latestActivity": "Dernière activité",
    "admin.overview.seeAll": "Tout voir",
    "admin.overview.empty": "Rien à afficher pour l'instant.",
    "admin.overview.managedBy": "managé par",

    // Admin — utilisateurs
    "admin.users.allRoles": "Tous les rôles",
    "admin.users.addUser": "Ajouter",
    "admin.users.manager": "Manager",
    "admin.users.noManager": "— Aucun",
    "admin.users.pendingFirstLogin": "1re connexion",
    "admin.users.new.title": "Provisionner un accès",
    "admin.users.new.subtitle": "Compte EY avec mot de passe généré et envoyé par email.",
    "admin.users.new.firstName": "Prénom",
    "admin.users.new.lastName": "Nom",
    "admin.users.new.email": "Email EY",
    "admin.users.new.role": "Rôle",
    "admin.users.new.manager": "Manager",
    "admin.users.new.optional": "optionnel",
    "admin.users.new.emailInfo": "Un mot de passe fort est généré automatiquement et envoyé à cette adresse avec les identifiants de connexion. L'utilisateur devra le changer à la première connexion.",
    "admin.users.new.creating": "Création…",
    "admin.users.new.create": "Créer le compte",
    "admin.users.new.createdTitle": "Compte créé",
    "admin.users.new.emailSent": "Les identifiants ont été envoyés par email à l'utilisateur.",
    "admin.users.new.emailNotSent": "Email non configuré (SMTP) — transmettez ce mot de passe temporaire :",
    "admin.users.new.copy": "Copier",
    "admin.users.new.copied": "Copié ✓",
    "admin.users.new.passwordOnce": "Affiché une seule fois — il n'est stocké nulle part en clair.",
    "admin.users.new.done": "Terminer",
    "admin.users.new.nameRequired": "Prénom et nom requis.",
    "admin.users.new.domainError": "Seules les adresses @tn.ey.com sont autorisées.",
    "admin.users.new.managerRequired": "Chaque consultant doit être rattaché à un manager.",
    "admin.users.new.failed": "Échec de la création.",
    "admin.users.new.tab": "Nouvel utilisateur",
    "admin.users.new.noManagerRole": "Ce rôle n'a pas de manager.",

    // Admin — réclamations
    "admin.recl.title": "Réclamations",
    "admin.recl.subtitle": "Bugs et demandes remontés par les utilisateurs.",
    "admin.recl.pendingCount": "en attente",
    "admin.recl.all": "Toutes",
    "admin.recl.pending": "En attente",
    "admin.recl.resolved": "Résolue",
    "admin.recl.emptyTitle": "Aucune réclamation",
    "admin.recl.emptyHint": "Tout est réglé — rien à traiter.",
    "admin.recl.resolve": "Résoudre",
    "admin.recl.reopen": "Rouvrir",
    "admin.recl.adminNote": "Note de l'équipe",
    "admin.recl.resolvedOn": "Résolue le",
    "admin.recl.resolveTitle": "Marquer comme résolue",
    "admin.recl.notePlaceholder": "Note pour l'utilisateur (optionnel)…",
    "admin.recl.cancel": "Annuler",
    "admin.recl.markResolved": "Résolu ✓",

    // Admin — activité
    "admin.activity.title": "Activité de la plateforme",
    "admin.activity.subtitle": "Journal de toutes les actions, tous rôles confondus.",
    "admin.activity.all": "Tout",
    "admin.activity.auth": "Connexions",
    "admin.activity.accounts": "Comptes",
    "admin.activity.work": "Travail",
    "admin.activity.refresh": "Actualiser",
    "admin.activity.empty": "Aucune activité.",
    "admin.activity.loadMore": "Charger plus",

    // Admin — base de connaissances (placeholder)
    "admin.knowledge.title": "Base de connaissances",
    "admin.knowledge.subtitle": "Gouvernance du graphe légal — ingestion et validation des textes.",
    "admin.knowledge.comingSoon": "Bientôt disponible",
    "admin.knowledge.heroTitle": "Ingestion des nouveaux textes légaux",
    "admin.knowledge.heroText": "Ce module permettra de découper (chunking) les nouveaux documents juridiques, de les vectoriser et de les intégrer au graphe de connaissances — sous votre contrôle.",
    "admin.knowledge.step.upload": "Dépôt",
    "admin.knowledge.step.uploadDesc": "Chargement des textes légaux (JORT, codes, conventions).",
    "admin.knowledge.step.chunking": "Chunking",
    "admin.knowledge.step.chunkingDesc": "Découpage sémantique et vectorisation des passages.",
    "admin.knowledge.step.review": "Validation",
    "admin.knowledge.step.reviewDesc": "Revue humaine de chaque lot avant intégration.",
    "admin.knowledge.step.publish": "Publication",
    "admin.knowledge.step.publishDesc": "Injection dans le graphe Neo4j et disponibilité en recherche.",
    "admin.knowledge.gateTitle": "Barrière de validation",
    "admin.knowledge.gateText": "aucune donnée non revue n'entre dans le graphe : chaque lot doit être approuvé par un administrateur avant publication.",

    // Manager — équipe
    "manager.team.title": "Mes consultants",
    "manager.team.subtitle": "Votre équipe, ses tâches et ses livrables.",
    "manager.team.toReview": "livrable(s) à valider",
    "manager.team.emptyTitle": "Aucun consultant rattaché",
    "manager.team.emptyHint": "Demandez à un administrateur de rattacher des consultants à votre équipe.",
    "manager.team.submittedBadge": "soumis",
    "manager.team.consultations": "consultations",
    "manager.team.lastLogin": "Vu le",
    "manager.detail.back": "Retour à l'équipe",
    "manager.detail.memberSince": "membre depuis",
    "manager.detail.assignTask": "Assigner une tâche",
    "manager.detail.tasks": "Tâches",
    "manager.detail.awaitingReview": "à valider",
    "manager.detail.allStatuses": "Tous les statuts",
    "manager.detail.noTasks": "Aucune tâche",
    "manager.detail.noTasksHint": "Assignez une première tâche de consultation à ce consultant.",
    "manager.assign.title": "Nouvelle tâche de consultation",
    "manager.assign.for": "Pour",
    "manager.assign.taskTitle": "Titre",
    "manager.assign.taskTitlePh": "Ex. Consultation RAS dividendes — Client X",
    "manager.assign.description": "Description",
    "manager.assign.descriptionPh": "Contexte, question fiscale, points d'attention…",
    "manager.assign.client": "Client",
    "manager.assign.priority": "Priorité",
    "manager.assign.dueDate": "Échéance",
    "manager.assign.collaborators": "Collaborateurs (email)",
    "manager.assign.add": "Ajouter",
    "manager.assign.collaboratorsHint": "Invitez d'autres consultants à collaborer — ils verront la tâche dans leur espace.",
    "manager.assign.assigning": "Assignation…",
    "manager.assign.assign": "Assigner la tâche",
    "manager.assign.invalidEmail": "Adresse email invalide.",
    "manager.assign.titleRequired": "Le titre est requis.",
    "manager.assign.failed": "Échec de la création de la tâche.",
    "manager.assign.skipped": "Emails introuvables (ignorés)",

    // Tâches (consultant)
    "tasks.title": "Mes tâches",
    "tasks.subtitle": "Tâches assignées par votre manager et collaborations.",
    "tasks.tabOpen": "À faire",
    "tasks.tabDone": "Soumises",
    "tasks.emptyOpen": "Aucune tâche en cours",
    "tasks.emptyOpenHint": "Les tâches assignées par votre manager apparaîtront ici.",
    "tasks.emptyDone": "Aucune tâche soumise",
    "tasks.emptyDoneHint": "Vos livrables soumis au manager apparaîtront ici.",
    "tasks.status.Pending": "En attente",
    "tasks.status.InProgress": "En cours",
    "tasks.status.Submitted": "Soumise",
    "tasks.status.Approved": "Validée",
    "tasks.priority.Low": "Basse",
    "tasks.priority.Medium": "Moyenne",
    "tasks.priority.High": "Haute",
    "tasks.priority.Urgent": "Urgente",
    "tasks.start": "Commencer",
    "tasks.workOnIt": "Créer la consultation",
    "tasks.submit": "Soumettre",
    "tasks.awaitingManager": "En attente de validation du manager",
    "tasks.approvedByManager": "Validée par le manager",
    "tasks.collab": "Collab",
    "tasks.from": "De",
    "tasks.due": "échéance",
    "tasks.assignedOn": "Assignée le",
    "tasks.collaborators": "Collaborateurs",
    "tasks.open": "Ouvrir",
    "tasks.viewExport": "Visualiser / Exporter",
    "tasks.deliverable": "Livrable soumis",
    "tasks.noConsultationLinked": "Aucune consultation liée à la soumission.",
    "tasks.sendBack": "Renvoyer pour révision",
    "tasks.approve": "Valider",
    "tasks.delete": "Supprimer",
    "tasks.timeline.assigned": "Assignée",
    "tasks.timeline.started": "Commencée",
    "tasks.timeline.notStarted": "non commencée",
    "tasks.timeline.submitted": "Soumise",
    "tasks.timeline.notSubmitted": "non soumise",
    "tasks.submitModal.title": "Soumettre le travail au manager",
    "tasks.submitModal.pickConsultation": "Consultation à joindre",
    "tasks.submitModal.noConsultations": "Aucune consultation.",
    "tasks.submitModal.createOne": "Créez-en une d'abord.",
    "tasks.submitModal.note": "Note pour le manager",
    "tasks.submitModal.notePh": "Points d'attention, hypothèses retenues… (optionnel)",
    "tasks.submitModal.submit": "Soumettre ✓",

    // Support
    "support.title": "Support & réclamations",
    "support.subtitle": "Signalez un bug ou une anomalie — l'équipe d'administration suit chaque demande.",
    "support.reportTitle": "Signaler un problème",
    "support.category": "Catégorie",
    "support.cat.Bug": "Bug",
    "support.cat.Data": "Donnée erronée",
    "support.cat.Feature": "Suggestion",
    "support.cat.Access": "Accès",
    "support.cat.Other": "Autre",
    "support.subject": "Sujet",
    "support.subjectPh": "Ex. Erreur lors de l'export Word",
    "support.description": "Description",
    "support.descriptionPh": "Décrivez le problème, les étapes pour le reproduire…",
    "support.send": "Envoyer la réclamation",
    "support.sending": "Envoi…",
    "support.sent": "Réclamation envoyée — l'équipe la traitera au plus vite.",
    "support.required": "Sujet et description requis.",
    "support.failed": "Échec de l'envoi.",
    "support.myReports": "Mes réclamations",
    "support.emptyTitle": "Aucune réclamation",
    "support.emptyHint": "Vos signalements et leur statut apparaîtront ici.",
    "support.pending": "En attente",
    "support.resolved": "Résolue",
    "support.teamReply": "Réponse de l'équipe",
  },
  en: {
    // Sidebar
    "sidebar.workspace": "Workspace",
    "sidebar.dashboard": "Dashboard",
    "sidebar.search": "Search",
    "sidebar.chat": "AI Assistant",
    "sidebar.consultations": "Consultations",
    "sidebar.admin": "Administration",
    "sidebar.users": "Users",
    "sidebar.settings": "Settings",

    // Dashboard
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.subtitle":
      "Your tax copilot — research, advice and sourced consultations.",
    "dashboard.askQuestion": "Ask a question",
    "dashboard.newConsultation": "New consultation",
    "dashboard.kpi.consultations": "Consultations",
    "dashboard.kpi.consultationsHint": "total",
    "dashboard.kpi.consultationsThisWeek": "this week",
    "dashboard.kpi.chunks": "Indexed legal base",
    "dashboard.kpi.chunksHint": "passages in the Tunisian corpus",
    "dashboard.kpi.entities": "Graph entities",
    "dashboard.kpi.entitiesHint": "connected in Neo4j",
    "dashboard.kpi.clients": "Active clients",
    "dashboard.kpi.clientsHint": "Unique client files",
    "dashboard.activity": "Activity",
    "dashboard.last7days": "last 7 days",
    "dashboard.kb": "Knowledge base",
    "dashboard.recent": "Recent consultations",
    "dashboard.seeAll": "See all",
    "dashboard.noConsultations": "No consultations",
    "dashboard.noConsultationsHint": "Generate your first tax memo.",
    "dashboard.createConsultation": "Create a consultation",
    "dashboard.quickActions": "Quick actions",
    "dashboard.qa.search": "Search the law",
    "dashboard.qa.searchDesc": "Codes, treaties & doctrine",
    "dashboard.qa.chat": "Ask the assistant",
    "dashboard.qa.chatDesc": "Instant sourced answers",
    "dashboard.qa.newConsultation": "New consultation",
    "dashboard.qa.newConsultationDesc": "Structured memo in ~1 minute",
    "dashboard.qa.users": "Manage users",
    "dashboard.qa.usersDesc": "Roles, access & activity",

    // JORT
    "jort.title": "Official Gazette (JORT)",
    "jort.seeAll": "See all",
    "jort.new": "New",

    // Chat bubble
    "chat.title": "Tax assistant",
    "chat.subtitle": "Answers sourced from the corpus",
    "chat.placeholder": "Quick tax question…",
    "chat.intro": "A quick question?",
    "chat.introHint": "Ask without leaving the page.",

    // Chat page
    "chat.newChat": "New chat",
    "chat.hideHistory": "Hide history",
    "chat.showHistory": "Show history",
    "chat.conversationHistory": "Conversation history",
    "chat.noConversations": "No conversations",
    "chat.noConversationsHint":
      "Your exchanges with the assistant will appear here.",
    "chat.today": "Today",
    "chat.yesterday": "Yesterday",
    "chat.last7days": "Last 7 days",
    "chat.last30days": "Last 30 days",
    "chat.older": "Older",
    "chat.justNow": "just now",
    "chat.minutesAgo": "{n} min ago",
    "chat.hoursAgo": "{n}h ago",
    "chat.exchange": "exchange",
    "chat.exchanges": "exchanges",
    "chat.confirmDelete": "Confirm deletion",
    "chat.deleteConversation": "Delete conversation",
    "chat.clickToConfirm": "Click to confirm",
    "chat.greeting": "a tax question?",
    "chat.greetingDesc":
      "Every answer is grounded in the Tunisian legal corpus — with clickable cited sources.",
    "chat.inputPlaceholder": "Ask your tax question…",
    "chat.analyzing": "Analyzing question…",
    "chat.errorMsg":
      "Sorry — I couldn't answer. Check that Neo4j and the LLM are connected.",
    "chat.disclaimer":
      "AI-generated answers from the indexed corpus — verify the cited sources.",
    "chat.references": "References",
    "chat.sources": "Sources",
    "chat.closeTab": "Close tab",

    // Chat suggestions
    "chat.sug1.title": "Withholding tax",
    "chat.sug1.q":
      "What is the withholding tax rate on fees paid to a non-resident?",
    "chat.sug2.title": "Export VAT",
    "chat.sug2.q": "Is VAT due on services rendered to a foreign company?",
    "chat.sug3.title": "Transfer pricing",
    "chat.sug3.q": "How does the transfer pricing regime work in Tunisia?",
    "chat.sug4.title": "Tax treaty",
    "chat.sug4.q": "How does the Tunisia-France treaty handle dividends?",

    // Search page
    "search.lawTab": "Legal texts",
    "search.consultationsTab": "Consultations",
    "search.filters": "Filters",
    "search.clearAll": "Clear all",
    "search.textType": "Text type",
    "search.period": "Period",
    "search.from": "From",
    "search.to": "To",
    "search.client": "Client",
    "search.searchClient": "Search a client…",
    "search.creationDate": "Creation date",
    "search.fromDate": "From",
    "search.toDate": "To",
    "search.country": "Country",
    "search.keywords": "Keywords",
    "search.recent": "Recent",
    "search.searchLaw": "Search legal texts…",
    "search.searchConsultations": "Search consultations…",
    "search.searchBtn": "Search",
    "search.results": "results",
    "search.consultation": "consultation",
    "search.consultations": "consultations",
    "search.whatLooking": "What are you looking for?",
    "search.lawHint": "Semantic search across 67,000+ legal passages.",
    "search.consHint": "Find a memo by client, reference, or keywords.",
    "search.noLawResults": "No texts found",
    "search.noLawHint": "Broaden your keywords or reset the filters.",
    "search.noConsResults": "No consultations",
    "search.noConsHint": "Try a different client name or reference.",
    "search.all": "All",
    "search.codes": "Codes",
    "search.conventions": "Conventions",
    "search.loisFinances": "Finance laws",
    "search.doctrine": "Doctrine",
    "search.commentaires": "Comments",
    "search.searchFailed": "Search failed — check the engine connection.",

    // Consultations page
    "cons.newConsultation": "New consultation",
    "cons.memosGenerated": "memo{s} generated",
    "cons.describeCase": "Describe the case.",
    "cons.describeHint":
      "AI drafts a structured and sourced memo from the legal corpus — in about one minute.",
    "cons.theCase": "The case",
    "cons.clientName": "Client name",
    "cons.clientPlaceholder": "Company X",
    "cons.reference": "Reference",
    "cons.optional": "optional",
    "cons.theSituation": "The situation",
    "cons.factualContext": "Factual context",
    "cons.situationPlaceholder":
      "Who are the parties, what operations, what amounts, what countries…",
    "cons.characters": "characters",
    "cons.min20": "min. 20",
    "cons.theQuestion": "The question",
    "cons.fiscalQuestion": "Tax question to resolve",
    "cons.questionPlaceholder": "What is the tax question to address?",
    "cons.min10": "min. 10",
    "cons.consultationFormat": "Consultation format",
    "cons.detailed": "Detailed version",
    "cons.detailedDesc":
      "Principle, application to the facts, and conclusion for each point.",
    "cons.concise": "Concise version",
    "cons.conciseDesc":
      "Straight to the point: the verdict and its source, no elaboration.",
    "cons.generate": "Generate consultation",
    "cons.fillFields":
      "Fill in the client, situation, and question to start generation.",
    "cons.generating": "Drafting the consultation",
    "cons.generatingHint": "Usually less than a minute.",
    "cons.memoPreview": "Memo preview",
    "cons.includeTips": "Include if possible",
    "cons.generated": "Consultation generated.",
    "cons.generateFailed": "Generation failed. Check the engine status — Neo4j and the LLM must be connected.",
    "cons.confirmLeave": "Generation in progress — leave this page?",
    "cons.confirmDiscard": "The current draft will be lost — continue?",
    "cons.hideList": "Hide list",
    "cons.showList": "Show list",
    "cons.previousConsultations": "Previous consultations",
    "cons.memos": "memo",
    "cons.pipeline1": "Detecting branches & jurisdiction",
    "cons.pipeline1d": "CIT · PIT · VAT · Withholding · Transfer pricing",
    "cons.pipeline2": "Semantic corpus search",
    "cons.pipeline2d": "Multilingual embeddings on 67k passages",
    "cons.pipeline3": "Source retrieval (Neo4j)",
    "cons.pipeline3d": "Treaties → codes → finance laws → doctrine",
    "cons.pipeline4": "Drafting context, scope & summary",
    "cons.pipeline4d": "Phase 1",
    "cons.pipeline5": "Analysis & summary table",
    "cons.pipeline5d": "Phases 2 ‖ 3 — in parallel",
    "cons.pipeline6": "Citation resolution & finalization",
    "cons.pipeline6d": "Every assertion traced to its source",
    "cons.tip1": "Legal form and tax residency of the parties",
    "cons.tip2": "Nature and amounts of the operations involved",
    "cons.tip3": "Countries involved if the case is international",
    "cons.tip4": "Dates and fiscal years concerned",
    "cons.example1": "What is the tax treatment of these royalties paid to the French provider?",
    "cons.example2": "Does the company benefit from a tax incentive for this investment?",
    "cons.example3": "What withholding tax obligations apply?",
    "cons.previewContext": "Context & facts",
    "cons.previewScope": "Scope of work",
    "cons.previewSummary": "Executive summary",
    "cons.previewAnalysis": "Analysis",
    "cons.previewDocs": "Documents & references",
    "cons.previewFooter": "+ summary table and numbered legal sources, all editable with AI after generation.",

    // Settings page
    "settings.title": "Settings",
    "settings.profile": "Profile",
    "settings.security": "Security",
    "settings.changePassword": "Change password",
    "settings.secureAccount": "Secure your account",
    "settings.activeSessions": "Active sessions",
    "settings.logoutAll": "Sign out everywhere",
    "settings.loading": "Loading…",
    "settings.noSessions": "No active sessions.",
    "settings.thisDevice": "This device",
    "settings.unknownIP": "Unknown IP",
    "settings.revoke": "Revoke",
    "settings.account": "Account",
    "settings.logout": "Sign out",
    "settings.lastLogin": "Last login",

    // Admin Users
    "admin.users.title": "Users",
    "admin.users.subtitle": "Manage roles, access, and activity.",
    "admin.users.search": "Search…",
    "admin.users.searchBtn": "Search",
    "admin.users.name": "Name",
    "admin.users.email": "Email",
    "admin.users.role": "Role",
    "admin.users.status": "Status",
    "admin.users.actions": "Actions",
    "admin.users.active": "Active",
    "admin.users.locked": "Locked",
    "admin.users.lock": "Lock",
    "admin.users.unlock": "Unlock",
    "admin.users.promote": "Promote to Admin",
    "admin.users.demote": "Demote to User",
    "admin.users.activity": "Activity",
    "admin.users.hide": "Hide",
    "admin.users.previous": "Previous",
    "admin.users.next": "Next",
    "admin.users.page": "Page",
    "admin.users.of": "of",
    "admin.users.loading": "Loading…",
    "admin.users.noUsers": "No users found.",
    "admin.users.you": "you",
    "admin.users.lastLogin": "Last login",
    "admin.users.recentActivity": "Recent activity",
    "admin.users.noActivity": "No activity recorded.",
    "admin.users.usersLabel": "users",
    "admin.users.user": "User",

    // System Status
    "system.checking": "Checking…",
    "system.allOnline": "All online",
    "system.issue": "Issue",
    "system.api": ".NET API",
    "system.neo4j": "Neo4j",
    "system.elastic": "Elasticsearch",
    "system.embed": "Embeddings",
    "system.connected": "Connected",
    "system.setupNeeded": "Setup needed",
    "system.engineStatus": "Engine status",
    "system.knowledgeBase": "Knowledge base (Neo4j)",
    "system.aiModel": "AI model (LLM)",
    "system.embedServer": "Embedding server",
    "system.chunksIndexed": "{n} chunks indexed",
    "system.configured": "Configured",
    "system.neo4jHint": "Set Neo4j:Password in appsettings.Development.json and restart the API.",
    "system.llmHint": "Add a valid OpenAI:ApiKey in appsettings.Development.json.",
    "system.embedRunning": "Running on :8081",
    "system.embedHint": "Optional — run ./start-embed-server.sh for vector search.",

    // Editor
    "editor.aiCoWriter": "AI Co-writer",
    "editor.aiCoWriterHint": "Edit the document in natural language",
    "editor.hidePanel": "Hide panel",
    "editor.target": "Target",
    "editor.modifyNaturalLanguage": "Edit the document in natural language.",
    "editor.selectPassage": "Select a passage in the document, or target a section and describe the change:",
    "editor.example1": "Add a VAT analysis for non-residents.",
    "editor.example2": "Rephrase the summary more concisely.",
    "editor.example3": "Cite the Tunisia-France convention on dividends.",
    "editor.rewriting": "Rewriting",
    "editor.modify": "Edit",
    "editor.refineFailed": "The modification failed. Check that the LLM is connected.",
    "editor.saved": "Saved",
    "editor.save": "Save",
    "editor.saveFailed": "Save failed.",
    "editor.exportSuccess": "Word document exported.",
    "editor.exportFailed": "Export failed.",
    "editor.rated": "Rated",
    "editor.rate": "Rate",
    "editor.unsavedWarning": "Unsaved changes — switch document anyway?",
    "editor.unsaved": "Unsaved changes",
    "editor.hideList": "Hide list",
    "editor.showList": "Show list",
    "editor.allConsultations": "All consultations",
    "editor.opening": "Opening document…",
    "editor.aiAssistant": "AI Assistant",
    "editor.expertise": "Accounting expertise & tax advisory",
    "editor.fiscalConsultation": "Tax consultation notice",
    "editor.consultationSubtitle": "Advisory note — Tax situation",
    "editor.reference": "Reference",
    "editor.date": "Date",
    "editor.recipient": "Recipient",
    "editor.author": "Author",
    "editor.subject": "Subject",
    "editor.analysis": "Analysis",
    "editor.conclusion": "Conclusion",
    "editor.legalSources": "Legal sources",
    "editor.confidential": "Confidential document — Do not distribute",
    "editor.modifyWith": "Edit with AI",
    "editor.selectedPassage": "Selected passage",
    "editor.describeModification": "Or describe the modification…",

    // Sidebar (roles)
    "sidebar.tasks": "My tasks",
    "sidebar.management": "Management",
    "sidebar.consultants": "Consultants",
    "sidebar.adminOverview": "Overview",
    "sidebar.reclamations": "Reclamations",
    "sidebar.activity": "Activity",
    "sidebar.knowledge": "Knowledge base",
    "sidebar.support": "Support",

    // Admin — overview
    "admin.overview.title": "Administration",
    "admin.overview.subtitle": "Platform governance — users, roles and oversight.",
    "admin.overview.addUser": "Add user",
    "admin.overview.reviewReclamations": "Reclamations",
    "admin.overview.kpi.users": "Users",
    "admin.overview.kpi.thisMonth": "this month",
    "admin.overview.kpi.reclamations": "Pending reclamations",
    "admin.overview.kpi.resolved": "resolved",
    "admin.overview.kpi.consultations": "Consultations",
    "admin.overview.kpi.thisWeek": "this week",
    "admin.overview.kpi.tasks": "Tasks in flight",
    "admin.overview.kpi.awaitingReview": "awaiting review",
    "admin.overview.roleDistribution": "Role distribution",
    "admin.overview.locked": "locked",
    "admin.overview.recentUsers": "Recent registrations",
    "admin.overview.latestActivity": "Latest activity",
    "admin.overview.seeAll": "See all",
    "admin.overview.empty": "Nothing to show yet.",
    "admin.overview.managedBy": "managed by",

    // Admin — users
    "admin.users.allRoles": "All roles",
    "admin.users.addUser": "Add user",
    "admin.users.manager": "Manager",
    "admin.users.noManager": "— None",
    "admin.users.pendingFirstLogin": "1st login",
    "admin.users.new.title": "Provision access",
    "admin.users.new.subtitle": "EY account with a generated password emailed to the user.",
    "admin.users.new.firstName": "First name",
    "admin.users.new.lastName": "Last name",
    "admin.users.new.email": "EY email",
    "admin.users.new.role": "Role",
    "admin.users.new.manager": "Manager",
    "admin.users.new.optional": "optional",
    "admin.users.new.emailInfo": "A strong password is generated automatically and emailed to this address along with the login credentials. The user must change it on first login.",
    "admin.users.new.creating": "Creating…",
    "admin.users.new.create": "Create account",
    "admin.users.new.createdTitle": "Account created",
    "admin.users.new.emailSent": "Credentials were emailed to the user.",
    "admin.users.new.emailNotSent": "Email not configured (SMTP) — share this temporary password:",
    "admin.users.new.copy": "Copy",
    "admin.users.new.copied": "Copied ✓",
    "admin.users.new.passwordOnce": "Shown only once — it is never stored in clear.",
    "admin.users.new.done": "Done",
    "admin.users.new.nameRequired": "First and last name are required.",
    "admin.users.new.domainError": "Only @tn.ey.com addresses are allowed.",
    "admin.users.new.managerRequired": "Every consultant must be attached to a manager.",
    "admin.users.new.failed": "Creation failed.",
    "admin.users.new.tab": "New user",
    "admin.users.new.noManagerRole": "This role has no manager.",

    // Admin — reclamations
    "admin.recl.title": "Reclamations",
    "admin.recl.subtitle": "Bugs and requests reported by users.",
    "admin.recl.pendingCount": "pending",
    "admin.recl.all": "All",
    "admin.recl.pending": "Pending",
    "admin.recl.resolved": "Resolved",
    "admin.recl.emptyTitle": "No reclamations",
    "admin.recl.emptyHint": "All clear — nothing to handle.",
    "admin.recl.resolve": "Resolve",
    "admin.recl.reopen": "Reopen",
    "admin.recl.adminNote": "Team note",
    "admin.recl.resolvedOn": "Resolved on",
    "admin.recl.resolveTitle": "Mark as resolved",
    "admin.recl.notePlaceholder": "Note for the user (optional)…",
    "admin.recl.cancel": "Cancel",
    "admin.recl.markResolved": "Resolved ✓",

    // Admin — activity
    "admin.activity.title": "Platform activity",
    "admin.activity.subtitle": "Log of every action, across all roles.",
    "admin.activity.all": "All",
    "admin.activity.auth": "Sign-ins",
    "admin.activity.accounts": "Accounts",
    "admin.activity.work": "Work",
    "admin.activity.refresh": "Refresh",
    "admin.activity.empty": "No activity.",
    "admin.activity.loadMore": "Load more",

    // Admin — knowledge base (placeholder)
    "admin.knowledge.title": "Knowledge base",
    "admin.knowledge.subtitle": "Legal graph governance — ingestion and validation of new texts.",
    "admin.knowledge.comingSoon": "Coming soon",
    "admin.knowledge.heroTitle": "Ingestion of new legal documents",
    "admin.knowledge.heroText": "This module will chunk new legal documents, embed them and integrate them into the knowledge graph — under your control.",
    "admin.knowledge.step.upload": "Upload",
    "admin.knowledge.step.uploadDesc": "Load legal texts (JORT, codes, treaties).",
    "admin.knowledge.step.chunking": "Chunking",
    "admin.knowledge.step.chunkingDesc": "Semantic splitting and embedding of passages.",
    "admin.knowledge.step.review": "Review",
    "admin.knowledge.step.reviewDesc": "Human review of every batch before integration.",
    "admin.knowledge.step.publish": "Publish",
    "admin.knowledge.step.publishDesc": "Injection into the Neo4j graph, available in search.",
    "admin.knowledge.gateTitle": "Approval gate",
    "admin.knowledge.gateText": "no unreviewed data enters the graph: every batch must be approved by an administrator before publication.",

    // Manager — team
    "manager.team.title": "My consultants",
    "manager.team.subtitle": "Your team, their tasks and deliverables.",
    "manager.team.toReview": "deliverable(s) to review",
    "manager.team.emptyTitle": "No consultants attached",
    "manager.team.emptyHint": "Ask an administrator to attach consultants to your team.",
    "manager.team.submittedBadge": "submitted",
    "manager.team.consultations": "consultations",
    "manager.team.lastLogin": "Seen",
    "manager.detail.back": "Back to team",
    "manager.detail.memberSince": "member since",
    "manager.detail.assignTask": "Assign a task",
    "manager.detail.tasks": "Tasks",
    "manager.detail.awaitingReview": "awaiting review",
    "manager.detail.allStatuses": "All statuses",
    "manager.detail.noTasks": "No tasks",
    "manager.detail.noTasksHint": "Assign this consultant their first consultation task.",
    "manager.assign.title": "New consultation task",
    "manager.assign.for": "For",
    "manager.assign.taskTitle": "Title",
    "manager.assign.taskTitlePh": "E.g. WHT consultation on dividends — Client X",
    "manager.assign.description": "Description",
    "manager.assign.descriptionPh": "Context, fiscal question, points of attention…",
    "manager.assign.client": "Client",
    "manager.assign.priority": "Priority",
    "manager.assign.dueDate": "Due date",
    "manager.assign.collaborators": "Collaborators (email)",
    "manager.assign.add": "Add",
    "manager.assign.collaboratorsHint": "Invite other consultants to collaborate — the task will appear in their workspace.",
    "manager.assign.assigning": "Assigning…",
    "manager.assign.assign": "Assign task",
    "manager.assign.invalidEmail": "Invalid email address.",
    "manager.assign.titleRequired": "A title is required.",
    "manager.assign.failed": "Failed to create the task.",
    "manager.assign.skipped": "Emails not found (skipped)",

    // Tasks (consultant)
    "tasks.title": "My tasks",
    "tasks.subtitle": "Tasks assigned by your manager and collaborations.",
    "tasks.tabOpen": "To do",
    "tasks.tabDone": "Submitted",
    "tasks.emptyOpen": "No open tasks",
    "tasks.emptyOpenHint": "Tasks assigned by your manager will appear here.",
    "tasks.emptyDone": "No submitted tasks",
    "tasks.emptyDoneHint": "Deliverables submitted to your manager will appear here.",
    "tasks.status.Pending": "Pending",
    "tasks.status.InProgress": "In progress",
    "tasks.status.Submitted": "Submitted",
    "tasks.status.Approved": "Approved",
    "tasks.priority.Low": "Low",
    "tasks.priority.Medium": "Medium",
    "tasks.priority.High": "High",
    "tasks.priority.Urgent": "Urgent",
    "tasks.start": "Start",
    "tasks.workOnIt": "Create consultation",
    "tasks.submit": "Submit",
    "tasks.awaitingManager": "Awaiting manager review",
    "tasks.approvedByManager": "Approved by manager",
    "tasks.collab": "Collab",
    "tasks.from": "From",
    "tasks.due": "due",
    "tasks.assignedOn": "Assigned on",
    "tasks.collaborators": "Collaborators",
    "tasks.open": "Open",
    "tasks.viewExport": "View / Export",
    "tasks.deliverable": "Submitted deliverable",
    "tasks.noConsultationLinked": "No consultation linked to the submission.",
    "tasks.sendBack": "Send back for rework",
    "tasks.approve": "Approve",
    "tasks.delete": "Delete",
    "tasks.timeline.assigned": "Assigned",
    "tasks.timeline.started": "Started",
    "tasks.timeline.notStarted": "not started",
    "tasks.timeline.submitted": "Submitted",
    "tasks.timeline.notSubmitted": "not submitted",
    "tasks.submitModal.title": "Submit work to your manager",
    "tasks.submitModal.pickConsultation": "Consultation to attach",
    "tasks.submitModal.noConsultations": "No consultations yet.",
    "tasks.submitModal.createOne": "Create one first.",
    "tasks.submitModal.note": "Note for your manager",
    "tasks.submitModal.notePh": "Points of attention, assumptions made… (optional)",
    "tasks.submitModal.submit": "Submit ✓",

    // Support
    "support.title": "Support & reclamations",
    "support.subtitle": "Report a bug or an issue — the admin team tracks every request.",
    "support.reportTitle": "Report an issue",
    "support.category": "Category",
    "support.cat.Bug": "Bug",
    "support.cat.Data": "Wrong data",
    "support.cat.Feature": "Suggestion",
    "support.cat.Access": "Access",
    "support.cat.Other": "Other",
    "support.subject": "Subject",
    "support.subjectPh": "E.g. Error during Word export",
    "support.description": "Description",
    "support.descriptionPh": "Describe the issue and the steps to reproduce it…",
    "support.send": "Send reclamation",
    "support.sending": "Sending…",
    "support.sent": "Reclamation sent — the team will handle it shortly.",
    "support.required": "Subject and description are required.",
    "support.failed": "Failed to send.",
    "support.myReports": "My reclamations",
    "support.emptyTitle": "No reclamations",
    "support.emptyHint": "Your reports and their status will appear here.",
    "support.pending": "Pending",
    "support.resolved": "Resolved",
    "support.teamReply": "Team reply",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem("taxmind.lang") || "fr",
  );

  useEffect(() => {
    localStorage.setItem("taxmind.lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key, params) => {
    let str = STRINGS[lang]?.[key] ?? STRINGS.fr[key] ?? key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
